/**
 * ISO 27001:2022 Annex A controls — French translations (AFNOR).
 *
 * The backend API returns control titles in English. This map provides
 * the official AFNOR French translations so that French-speaking auditors
 * (RSSI, DPO) see controls in their language.
 *
 * Source: ISO/IEC 27001:2022 — Annexe A (version française AFNOR).
 */

const controlTitlesFr: Record<string, string> = {
  'A.5.1': "Politiques de sécurité de l'information",
  'A.5.2': "Rôles et responsabilités en matière de sécurité de l'information",
  'A.5.3': "Séparation des tâches",
  'A.5.4': "Responsabilité de la direction",
  'A.5.5': "Contacts avec les autorités",
  'A.5.6': "Contacts avec des groupes d'intérêt spécifiques",
  'A.5.7': "Renseignement sur les menaces",
  'A.5.8': "Sécurité de l'information dans la gestion de projet",
  'A.5.9': "Inventaire des informations et des autres actifs associés",
  'A.5.10': "Usage acceptable des informations et des autres actifs associés",
  'A.5.11': "Restitution des actifs",
  'A.5.12': "Classification des informations",
  'A.5.13': "Étiquetage des informations",
  'A.5.14': "Transfert d'informations",
  'A.5.15': "Contrôle d'accès",
  'A.5.16': "Gestion des identités",
  'A.5.17': "Informations d'authentification",
  'A.5.18': "Droits d'accès",
  'A.5.19': "Sécurité de l'information dans les relations avec les fournisseurs",
  'A.5.20': "Traitement de la sécurité de l'information dans les accords avec les fournisseurs",
  'A.5.21': "Gestion de la sécurité de l'information dans la chaîne d'approvisionnement TIC",
  'A.5.22': "Surveillance, revue et gestion des changements des services des fournisseurs",
  'A.5.23': "Sécurité de l'information pour l'utilisation des services cloud",
  'A.5.24': "Planification et préparation de la gestion des incidents de sécurité de l'information",
  'A.5.25': "Évaluation et décision sur les événements de sécurité de l'information",
  'A.5.26': "Réponse aux incidents de sécurité de l'information",
  'A.5.27': "Apprentissage des incidents de sécurité de l'information",
  'A.5.28': "Collecte de preuves",
  'A.5.29': "Sécurité de l'information pendant les perturbations",
  'A.5.30': "Préparation des TIC pour la continuité d'activité",
  'A.5.31': "Exigences légales, statutaires, réglementaires et contractuelles",
  'A.5.32': "Droits de propriété intellectuelle",
  'A.5.33': "Protection des enregistrements",
  'A.5.34': "Confidentialité et protection des données à caractère personnel",
  'A.5.35': "Revue indépendante de la sécurité de l'information",
  'A.5.36': "Conformité aux politiques, règles et standards de sécurité de l'information",
  'A.5.37': "Procédures d'exploitation documentées",
  'A.6.1': "Habilitation",
  'A.6.2': "Termes et conditions d'emploi",
  'A.6.3': "Sensibilisation, éducation et formation à la sécurité de l'information",
  'A.6.4': "Procédure disciplinaire",
  'A.6.5': "Responsabilités après fin ou changement d'emploi",
  'A.6.6': "Accords de confidentialité ou de non-divulgation",
  'A.6.7': "Travail à distance",
  'A.6.8': "Signalement des événements de sécurité de l'information",
  'A.7.1': "Périmètres de sécurité physique",
  'A.7.2': "Entrée physique",
  'A.7.3': "Sécurisation des bureaux, salles et installations",
  'A.7.4': "Surveillance de la sécurité physique",
  'A.7.5': "Protection contre les menaces physiques et environnementales",
  'A.7.6': "Travail dans les zones sécurisées",
  'A.7.7': "Bureau propre et écran propre",
  'A.7.8': "Implantation et protection des équipements",
  'A.7.9': "Sécurité des actifs hors site",
  'A.7.10': "Supports de stockage",
  'A.7.11': "Services utilitaires",
  'A.7.12': "Sécurité du câblage",
  'A.7.13': "Maintenance des équipements",
  'A.7.14': "Élimination ou réutilisation sécurisée des équipements",
  'A.8.1': "Dispositifs utilisateurs finaux",
  'A.8.2': "Droits d'accès privilégiés",
  'A.8.3': "Restriction d'accès aux informations",
  'A.8.4': "Accès au code source",
  'A.8.5': "Authentification sécurisée",
  'A.8.6': "Gestion de la capacité",
  'A.8.7': "Protection contre les logiciels malveillants",
  'A.8.8': "Gestion des vulnérabilités techniques",
  'A.8.9': "Gestion de la configuration",
  'A.8.10': "Suppression d'informations",
  'A.8.11': "Masquage de données",
  'A.8.12': "Prévention des fuites de données",
  'A.8.13': "Sauvegarde des informations",
  'A.8.14': "Redondance des installations de traitement de l'information",
  'A.8.15': "Journalisation",
  'A.8.16': "Activités de surveillance",
  'A.8.17': "Synchronisation des horloges",
  'A.8.18': "Utilisation de programmes utilitaires privilégiés",
  'A.8.19': "Installation de logiciels sur des systèmes en production",
  'A.8.20': "Sécurité des réseaux",
  'A.8.21': "Sécurité des services réseau",
  'A.8.22': "Séparation des réseaux",
  'A.8.23': "Filtrage web",
  'A.8.24': "Utilisation de la cryptographie",
  'A.8.25': "Cycle de développement sécurisé",
  'A.8.26': "Exigences de sécurité des applications",
  'A.8.27': "Architecture et ingénierie de systèmes sécurisés",
  'A.8.28': "Codage sécurisé",
  'A.8.29': "Sécurité en développement et en acceptation",
  'A.8.30': "Développement externalisé",
  'A.8.31': "Séparation des environnements de développement, test et production",
  'A.8.32': "Gestion des changements",
  'A.8.33': "Informations de test",
  'A.8.34': "Protection des systèmes d'information lors des tests d'audit",
}

/**
 * Returns the French translation of an ISO 27001 control title.
 * Falls back to the original English title if no translation is available.
 */
export function translateControlTitle(controlId: string, originalTitle: string): string {
  return controlTitlesFr[controlId] ?? originalTitle
}